### ISSUE TITLE
Threading and Callbacks

### ISSUE THREAD

**Issue by AndreasGocht** [azlux/pymumble#121]
Hey,

I poked around in the callbacks code, and came to wonder, why there is a thread spawn for dealing with `PYMUMBLE_CLBK_TEXTMESSAGERECEIVED` but not for any other callback:

```
if self[callback]:
            for func in self[callback]:
                if callback is PYMUMBLE_CLBK_TEXTMESSAGERECEIVED:
                    thr = threading.Thread(target=func, args=pos_parameters)
                    thr.start()
                else:
                    func(*pos_parameters)
```

https://github.com/azlux/pymumble/blob/pymumble_py3/pymumble_py3/callbacks.py#L82

Is there a specific reason I just can't see?

I am trying to write a speech aware bot, which is also able to deal with Telegram.

Best,

Andreas

**Comment by azlux** [comment]
Hi @AndreasGocht,
I've added this threading because the action on textmessage can take time, and was freezing the bot (botamusique) enough to get disconnected.
Some message need time to be manage by bots.
It's more a workaround than a good fix. Good code should use ayncio. But I'm not good enough to transform this lib.

**Comment by AndreasGocht** [comment]
Thanks for the fast reply 😄 . That helped me a lot.

Best,

Andreas
