### ISSUE TITLE
Using pymumble with pyaudio, getting error on Ubuntu

### ISSUE THREAD

**Issue by Geberg** [azlux/pymumble#21]
Hi,
Im using pymumble to get audio from mumble user and pass it to audio output (headphones) using pyaudio.
On windows everything works fine, but on Ubuntu 14.04 on virtual machine Im still getting this error:
`Expression 'stream->playback.pcm' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4436`

I have tried several devices ids and also several Ubuntu versions, but no change.

Do you have any ideas why it happens, please? Sorry if its not too related to this project.
I appreciate any help, thanks.

Code:
I have pyaudio stream opened:
```
self.p_audio = pyaudio.PyAudio()
self.stream = self.p_audio.open(input=True,
                                output=True,
                                input_device_index=0,
                                output_device_index=1,
                                channels=1,
                                format=pyaudio.paInt16,
                                rate=pymumble.constants.PYMUMBLE_SAMPLERATE,
                                frames_per_buffer=1024)
```
And getting sound from user and trying to write it to stream:
```
while user.sound.is_sound():
    data = user.sound.get_sound(1024).pcm
    self.stream.write(data)
```

**Comment by azlux** [comment]
Hi,
I think it's more a ALSA issue. I don't use it so I cannot search for it. But some forum report this issue as well on Ubuntu with different program (capturing audio into audacity).
- Look at the comment [#8](https://bugs.launchpad.net/ubuntu/+source/audacity/+bug/1460498)
- [Here too](https://bugs.launchpad.net/ubuntu/+source/audacity/+bug/1223549)

I think you see the same issue because pymumble have some buffer and alsa don't wait for it. Check the comment to try if my analyze is good.
Srry but I cannot help that much.

Az
