### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by ughstudios** [azlux/pymumble#74]
This example does not work. 
https://github.com/azlux/pymumble/blob/pymumble_py3/examples/audio-only_client.py

I get this error:

```
Traceback (most recent call last):
  File "C:\Users\decil\Desktop\mumble-python tests\mumble.py", line 26, in <module>
    import pymumble.pymumble_py3 as pymumble_py3
ModuleNotFoundError: No module named 'pymumble'
```

**Comment by azlux** [comment]
As refer to the readme, the import depend of the install method.
https://github.com/azlux/pymumble#installinggetting-started

If you install via pip, the import is different.

**Comment by DuckBoss** [comment]
I think it would be better to update the examples to use the new pip install method since that's what most people will be using.
(or document the examples to include that information). 
Or maybe it would be better to have two sets of examples instead based on import type. I can send a pull request if you need.
