### ISSUE TITLE
streaming music using ffmpeg

### ISSUE THREAD

**Issue by bitconnector** [azlux/pymumble#89]
Hello
I wanted to write a simple bot for testing purposes to play some music files.
I used the [talking_bot.py](https://github.com/azlux/pymumble/blob/pymumble_py3/examples/talking_bot.py) example as basis.
~~~
command = ["ffmpeg", "-i", file, "-ac", "1", "-f", "s32le", "-"]
sound = sp.Popen(command, stdout=sp.PIPE, stderr=sp.DEVNULL).stdout.read()
# sending speech to server
mumble.sound_output.add_sound(sound)
~~~
I always get this error message:
~~~
$ ./talking_bot2.py                                    1
Traceback (most recent call last):
  File "./talking_bot2.py", line 30, in <module>
    mumble.sound_output.add_sound(sound)
  File "/home/lukas/.local/lib/python3.8/site-packages/pymumble_py3/soundoutput.py", line 161, in add_sound
    samples = int(self.encoder_framesize * PYMUMBLE_SAMPLERATE * 2 * self.channels)  # number of samples in an encoder frame
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
~~~

**Comment by DuckBoss** [comment]
Hi, I worked on a bot that has music playing capabilities (https://github.com/DuckBoss/JJMumbleBot),
The major differences I did that works is:
1) setting the audio codec, "-acodec" to "pcm_s16le"  and "-f" to "s16le" instead of "s32le"
2) setting the audio rate, "-ar" to 24000 (use 48000 for stereo).
3) setting the bit rate, "-ab" to 192k
These parameters can be seen in the code snippet linked below: 
[Ffmpeg subprocess parameters](https://github.com/DuckBoss/JJMumbleBot/blob/b3aa6da70139c9dfc7ea9930bfe1bea309ffa73f/JJMumbleBot/lib/audio/audio_interface.py#L68-L79)

As far as reading the ffmpeg output, I read the output as 1024 byte buffers and add it into add_sound() using a while loop.
This can be seen in the code snippets linked below:
[Ffmpeg subprocess command](https://github.com/DuckBoss/JJMumbleBot/blob/b3aa6da70139c9dfc7ea9930bfe1bea309ffa73f/JJMumbleBot/lib/audio/audio_interface.py#L95)
[Reading from Ffmpeg and inputting to pymumble](https://github.com/DuckBoss/JJMumbleBot/blob/b3aa6da70139c9dfc7ea9930bfe1bea309ffa73f/JJMumbleBot/lib/audio/audio_interface.py#L103-L106)

<hr>
Hope this helps!

**Comment by bitconnector** [comment]
Thanks for your quick answer :D 
I changed my code acordingly
~~~
command = ["ffmpeg", "-i", file, "-acodec", "pcm_s16le", "-f", "s16le", "-ab", "192k", "-ac", "2", "-ar", "48000",  "-"]sound = sp.Popen(command, stdout=sp.PIPE, stderr=sp.DEVNULL, bufsize=1024)
# sending speech to server
while True:
   raw_music = sound.stdout.read(1024)
    if not raw_music:
    	break
    mumble.sound_output.add_sound(raw_music)
~~~
But I get the same error.
I also tried using audioop like used in the bot you refered to: `mumble.sound_output.add_sound(audioop.mul(raw_music, 2, 1))`
and I still get:
~~~
$ ./talking_bot2.py                                    1
Traceback (most recent call last):
  File "./talking_bot2.py", line 35, in <module>
    mumble.sound_output.add_sound(audioop.mul(raw_music, 2, 1))
  File "/home/lukas/.local/lib/python3.8/site-packages/pymumble_py3/soundoutput.py", line 161, in add_sound
    samples = int(self.encoder_framesize * PYMUMBLE_SAMPLERATE * 2 * self.channels)  # number of samples in an encoder frame
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
~~~

**Comment by DuckBoss** [comment]
Hmm, that's odd. I'm using v1.3.1 of pymumble  so maybe something related  to audio processing has changed  since then.
The only  other thing I've added which isn't  in the documentation is setting the audio codec profile for opus:
```
mumble.set_codec_profile('audio')
```
I've put this code before the mumble.start()/mumble.is_ready() commands.

Refer to the code  snippet  below which shows the usage in my bot:
[Setting The Audio Codec Profile - Code  Snippet](https://github.com/DuckBoss/JJMumbleBot/blob/b3aa6da70139c9dfc7ea9930bfe1bea309ffa73f/JJMumbleBot/core/bot_service.py#L164)

Refer to the source code in the pymumble library for  setting the audio codec profile:
[Audio Codec Profile - Pymumble Source Code Snippet](https://github.com/azlux/pymumble/blob/ab6bd98cf897aba96a30222b7a8926694b651918/pymumble_py3/mumble.py#L549-L554)

<hr>
If this doesn't solve  your problem,  I'm not sure what the issue is. It might be some change since  v1.3.1, so hopefully the pymumble developer @azlux can help you further.

**Comment by bitconnector** [comment]
Thanks @DuckBoss Its working now!!!
I just had to add `mumble.is_ready()` after `mumble.start()` :D

**Comment by ghost** [comment]
Hey, I just wanted to chime in with a problem I've been having and the solution for it.
# Setup (pre-conditions for repro)
## Server
I have a mumble server with `bandwidth=558000` in the config. This is 558kbps, which is [the max supported by opus](https://github.com/mumble-voip/mumble/pull/4700). The version of mumble server is 1.5.517

## pymumble code
```python
import time
import subprocess as sp
import pymumble_py3

mumble = pymumble_py3.Mumble('127.0.0.1', 'pymumble', stereo=True, debug=True)
mumble.set_codec_profile('audio')
mumble.start()
mumble.is_ready()   #wait for Mumble to get ready to avoid errors after startup

while True:
    print("start Processing")
    command = ["ffmpeg", "-i", '/home/rt/dev/mumble-subsonic/tracks/play.mp3', "-acodec", "pcm_s16le", "-f", "s16le", "-ab", "384k", "-ac", "2", "-ar", "48000", "-"]
    sound = sp.Popen(command, stdout=sp.PIPE, stderr=sp.DEVNULL, bufsize=1024)
    print("playing")
    while True:
        raw_music = sound.stdout.read(1024)
        if not raw_music:
            break
        mumble.sound_output.add_sound(raw_music)
    print("finished")
    while mumble.sound_output.get_buffer_size() > 0.5:  #
        time.sleep(0.01)
    print("sleep")
    time.sleep(2)
```

# The problem (repro)
1. Start mumble server with bandwidth=558000 in the config
2. Start the pymumble script above (python script.py) and try to play **stereo** audio (mono works fine)
3. The script's ffmpeg process is reading the file and sending it to pymumble (I can see because of debug=True) but it the pymumble bot is not playing anything in the Mumble channel. It's not even speaking - the icon is green (not speaking), but should be blue (speaking).

# The solution
In the script above, do this:
```diff
mumble.start()
mumble.is_ready()   #wait for Mumble to get ready to avoid errors after startup
+ mumble.set_bandwidth(192000)
```

For some reason, this makes the stereo audio play in Mumble just fine. Make sure to set_bandwidth() **AFTER** mumble.is_ready(), or else you'll get an error.

This solution wasn't necessary when playing mono audio (ffmpeg -ac 1), but hey - just throwing it out there so somebody can save a few days of debugging :P

Addmittedly, debug=True shows that pymumble is complaing a bit about the bandwdith setting:
```
2023-07-02 16:46:34,918-PyMumble-DEBUG-Bandwidth is 50000, downgrading to 30400 due to the protocol overhead
2023-07-02 16:46:34,920-PyMumble-DEBUG-Bandwidth is 558000, downgrading to 538400 due to the protocol ov
```
